import * as bcrypt from "https://deno.land/x/bcrypt@v0.4.1/mod.ts";
import * as nanoid from "https://deno.land/x/nanoid@v3.0.0/mod.ts";

export const SESSION_COOKIE_KEY = "session";

/**
 * Hash a password. A salt will be generated automatically if one is not provided.
 * @param password The plaintext password.
 * @param salt An optional salt generated by bcrypt.
 * @returns The hashed password.
 */
export async function hashPassword(password: string, salt?: string) {
  return await bcrypt.hash(password, salt);
}

/**
 * Checks if a given password matches a given hashed password.
 * @param plaintext The plaintext password.
 * @param hash The hashed password.
 * @returns The result of the comparison.
 */
export async function comparePasswords(plaintext: string, hash: string) {
  return await bcrypt.compare(plaintext, hash);
}

/**
 * An extremely basic way of generating a session.
 */
export function createSessionId() {
  const randomId = nanoid.nanoid();

  return randomId;
}
